// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Address string `json:"address"`
	Balance string `json:"balance"`
}

type Block struct {
	ID              string `json:"id"`
	Hash            string `json:"hash"`
	Number          string `json:"number"`
	Timestamp       string `json:"timestamp"`
	NumberOfTxs     string `json:"numberOfTxs"`
	Miner           string `json:"miner"`
	ParentHash      string `json:"parentHash"`
	Difficulty      string `json:"difficulty"`
	TotalDifficulty string `json:"totalDifficulty"`
	Size            string `json:"size"`
	GasUsed         string `json:"gasUsed"`
	GasLimit        string `json:"gasLimit"`
	Nonce           string `json:"nonce"`
	ExtraData       string `json:"extraData"`
}

type Query struct {
}

type Transaction struct {
	ID               string  `json:"id"`
	BlockHash        string  `json:"blockHash"`
	FromAddress      string  `json:"fromAddress"`
	ToAddress        string `json:"toAddress,omitempty"`
	Value            string  `json:"value"`
	Gas              string  `json:"gas"`
	GasPrice         string  `json:"gasPrice"`
	InputData        string  `json:"inputData"`
	Nonce            string  `json:"nonce"`
	TransactionIndex string  `json:"transactionIndex"`
	Timestamp        string  `json:"timestamp"`
}
