name: Go CI

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'golang/**'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'golang/**'
      - '.github/workflows/go.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOLANG_LOCATION: golang
  IMAGE_REPOSITORY: ghcr.io/synkube/gke

jobs:
  file-changes:
    name: file-changes
    runs-on: ubuntu-latest
    outputs:
      golang_dirs: ${{ steps.matrix.outputs.golang_dirs }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v35

      - name: Changed files matrix
        id: matrix
        env:
          MODIFIED_FILES: ${{ steps.changes.outputs.all_modified_files }}
        run: |
          # Enable debug mode
          set -x

          # Get the list of modified files
          modified_files=($(echo "$MODIFIED_FILES" | tr " " "\n"))

          # List of golang directories
          golang_dirs=($(ls golang | tr -d " "))

          echo "Golang directories: ${golang_dirs[@]}"

          # Array to hold changed golang directories
          changed_golang_dirs=()
          include_all_dirs=false

          for file in "${modified_files[@]}"; do
            if [[ $file =~ golang/core/.* ]]; then
              include_all_dirs=true
              break
            fi
          done

          if [ "$include_all_dirs" = true ]; then
            changed_golang_dirs=("${golang_dirs[@]}")
          else
            for golang_dir in "${golang_dirs[@]}"; do
              for file in "${modified_files[@]}"; do
                if [[ $file =~ golang/$golang_dir/.* ]]; then
                  changed_golang_dirs+=("$golang_dir")
                  break
                fi
              done
            done
          fi

          echo "Changed golang directories:"
          printf "%s\n" "${changed_golang_dirs[@]}"

          golang_output=$(jq -nc '[$ARGS.positional[]]' --args "${changed_golang_dirs[@]}")

          echo "golang_dirs=$golang_output" >> $GITHUB_OUTPUT

  go-build:
    runs-on: ubuntu-latest
    needs: [file-changes]
    if: ${{ needs.file-changes.outputs.golang_dirs != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        golang-app: ${{ fromJSON(needs.file-changes.outputs.golang_dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Install dependencies
        working-directory: ${{ env.GOLANG_LOCATION }}/${{ matrix.golang-app }}
        run: |
          go mod tidy
          go mod download

      - name: Cache Go build
        id: cache-go-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ matrix.golang-app }}

      - name: Run tests
        working-directory: ${{ env.GOLANG_LOCATION }}/${{ matrix.golang-app }}
        run: |
          go test -v ./...

      - name: Build
        working-directory: ${{ env.GOLANG_LOCATION }}/${{ matrix.golang-app }}
        run: |
          go build -o app

      - name: Run GoReleaser
        working-directory: ${{ env.GOLANG_LOCATION }}/${{ matrix.golang-app }}
        run: |
          goreleaser release
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ${{ env.GOLANG_LOCATION }}/${{ matrix.golang-app }}
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ matrix.golang-app }}:${{ github.sha }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Docker image
      #   run: docker push ghcr.io/${{ github.repository }}/${{ matrix.golang-app }}:${{ github.sha }}
